---
title: "Testing map for auto distance calculation"
author: "Francisko de Moraes Rezende"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fs)
library(plotly)
```

```{r}
files <- fs::dir_ls(here::here("subset-unpaired-points"))

files %>% 
  purrr::map_dfr(readr::read_csv, .id = "source") -> all_flights
```

```{r}
calc_flight_dist <- name <- function(dat) {
  dat_dist <-  {{dat}} %>% 
  dplyr::filter(!is.na(x_1)) %>%  # removes NA
  dist() %>%  # calculates distance
  as.matrix()  # converts it to a matrix

return(sum((dat_dist[row(dat_dist) == col(dat_dist) + 1])))  # sums the distance between points by summing the points in line n and column n + 1
  
}
```

```{r}
plots_flight_path <- function(dat) {
  
plotly::plot_ly(data = dat,
        type = "scatter3d", 
        x = dat$x_1 ,
        y = dat$y_1,
        z = dat$z_1,
        mode = "lines")
}
```

```{r}
straight_dist <- function(dat) {
  
dist_dat <- 
  dat %>% 
  dplyr::filter(!is.na(x_1)) %>%
  dist() %>% 
  as.matrix()

return(dist_dat[1, nrow(dist_dat)])  
}

```


```{r}
all_flights %>%
  dplyr::group_by(source) %>%
  tidyr::nest() %>% 
  dplyr::mutate(distance = purrr::map_dbl(data, ~ calc_flight_dist(.x)),
                plot_3d = purrr::map(data, ~ plots_flight_path(.x)),
                butterfly = stringr::str_extract(source, pattern = "b\\d{3}"),
                take = stringr::str_extract(source, pattern = "t\\d{1}")) 
# -> processed
```

```{r}
string <-  "/home/francisko/coding/r/flight-path-experiment/subset-unpaired-points/b195-t1-unpaired-points-xyz.csv"

str_extract(string, pattern = "b\\d{3}")

str_extract(string, pattern = "t\\d{1}")
```


```{r}
read_csv(here("subset-unpaired-points", "b211-t2-unpaired-points-xyz.csv")) %>% 
  calc_flight_dist()
```

```{r}
read_csv(here("subset-unpaired-points", "b211-t2-unpaired-points-xyz.csv")) %>% 
  straight_dist()
```


```{r}
read_csv(here("subset-unpaired-points", "b195-t1-unpaired-points-xyz.csv")) %>% 
  calc_flight_dist()
```

```{r}
read_csv(here("subset-unpaired-points", "b211-t2-unpaired-points-xyz.csv")) %>% 
  tibble::rowid_to_column(var = "row_number") %>% 
  tidyr::drop_na() %>%
  select(row_number) %>% 
  range()
```

Calculates how many rows there are after removing NaNs, might be useful to calculate speed.

```{r}
read_csv(here("subset-unpaired-points", "b211-t2-unpaired-points-xyz.csv")) %>% 
  tibble::rowid_to_column(var = "row_number") %>% 
  tidyr::drop_na() %>% 
  nrow()
```

